# 定义函数用于生成拟合函数的验证与测试数据
function1:
  name: function1
  expression: "200 * exp(-((x-1)**2 + (y-2)**2 + (z-3)**2 + (w-4)**2)) + 50 * sin(x) * cos(y) + log(1 + z**2 + w**2)"
  variables: [x,y,z,w] 
  max_point: {x: 1,y: 2,z: 3,w: 4}
  train:
    10000
  val:
    1000
  test:
    1000

function2:
  name : function2
  expression: "100  * sin(x) + 100 * cos(y)+w*z"
  variables: [x,y,z,w]
  train:
    1000000
  val:
    2000
  test:
    2000

function3:
  name : function3
  expression: "100 * x + y"
  variables: [x,y]
  train:
    50000
  val:
    200
  test:
    200

function4:
  name : function4
  expression: "sin(x)"
  variables: [x]
  train:
    10000
  val:
    200
  test:
    200

function5:
  name : function5
  expression: "3 * x + y + 5 * z + w"
  variables: [x,y,z,w]
  train:
    10000
  val:
    200
  test:
    200

function6:
  name : function6
  expression: "30 * x + y + 50 * z + w * 20 - e - 18 * r + t * 20 + 100 * g"
  variables: [x,y,z,w,e,r,t,g]
  train:
    50000
  val:
    200
  test:
    200



